sonar.projectKey=flowboard-payment-service
sonar.projectName=FlowBoard Payment Service
sonar.host.url=http://localhost:9000
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=**/dto/**,**/entity/**,**/*Application.java
sonar.java.source=23
sonar.sourceEncoding=UTF-8