sonar.projectKey=flowboard-list-service
sonar.projectName=FlowBoard List Service
sonar.host.url=http://localhost:9000
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=**/dto/**,**/entity/**,**/exception/**,**/*Application.java
sonar.java.source=17
sonar.sourceEncoding=UTF-8
